//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWASS6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeAssignment1
    {
        public int InstructorID { get; set; }
        public string Location { get; set; }
        public Nullable<System.TimeSpan> Timestamp { get; set; }
    
        public virtual Person1 Person1 { get; set; }
    }
}
